# -*- coding: utf-8 -*-
{
    'name': 'CFDI Multi Company',
    'version': '14.0.1.0.0',
    'summary': 'Permite seleccionar la compañía emisora al generar CFDI.',
    'category': 'Accounting',
    'author': 'Generated by ChatGPT',
    'depends': ['cdfi_invoice'],
    'data': [
        'wizard/cfdi_multi_company_wizard_view.xml',
        'views/account_move_report_templates.xml',
    ],
    'installable': True,
    'application': False,
}
